language: node_js
node_js:
  - "11"

script:
  - if [ "${TRAVIS_PULL_REQUEST}" != "false" ]; then npx audit-ci --low; else npx audit-ci --low || true; fi
  - npm run lint
  - npm test

deploy:
  - provider: script
    script: npm version --no-git-tag-version "${TRAVIS_TAG}" && npm publish --access public --apikey "${NPMJS_API_KEY}" --dry-run
    skip_cleanup: true
    on:
      tags: true
      condition: ${TRAVIS_TAG} =~ [0-9]+\.[0-9]+\.[0-9]+
